### ISSUE TITLE
修改针对placeholder的imap

### ISSUE THREAD

**Issue by yushangakki** [theniceboy/nvim#10]
有的时候在`,f` 之后发现复制的会是<++>,非常的不方便发现  `c4l` `x` `dd` 都一样，都会占用剪切板。
之后查了资料，我发现把`c4l` 改成 `"_c4l`就完美了。`"_` 表明 不占用clipboard，后面也直接可以用`dd`

此外谢谢您的bilibili视频和github config file，非常的有帮助。

**Comment by theniceboy** [comment]
非常感谢你的建议，我现在手头没有电脑，回去我会根据你的建议改掉，或者你也可以发一个pull request，我来合并也可以
