### ISSUE TITLE
how to fix the error in tabline

### ISSUE THREAD

**Issue by Innei** [theniceboy/nvim#11]
```
Error detected while processing function xtabline#hi#init[2]..xtabline#hi#apply_theme[7]..
14:
line   13:
E492: Not an editor command:  guifg=#af0000 gui=bold cterm=bold
```

**Comment by theniceboy** [comment]
More information needed

**Comment by Innei** [comment]
But 13 line is empty in init.vim.
![image](https://user-images.githubusercontent.com/41265413/72205513-db8b6e00-34be-11ea-887d-7ed13647deb7.png)
![image](https://user-images.githubusercontent.com/41265413/72205521-04abfe80-34bf-11ea-82b5-1c5af9b56c2e.png)

**Comment by Innei** [comment]
I just modify some keymap.

**Comment by theniceboy** [comment]
- how to reproduce
- :version

**Comment by Innei** [comment]
how to reproduce: Clone your repo into .config/nvim, then install pynvim (pip) and neovim (yarn). open nvim then to install Plugs. reopen the nvim. show this error. I try to create a docker subsystem which use Ubuntu and try again. Also show this error. This is the version on my mac.
![image](https://user-images.githubusercontent.com/41265413/72211765-b113d200-350b-11ea-9222-b07952d9b0e9.png)

This is the nvim version on the Ubuntu.
![image](https://user-images.githubusercontent.com/41265413/72211919-72334b80-350e-11ea-87c2-a076a9f4c3bb.png)

**Comment by Innei** [comment]
I needed to comment `Plug mg979/vim-xtabline`. It worked.

**Comment by Innei** [comment]
Fixed in <https://github.com/mg979/vim-xtabline/issues/6>.
