### ISSUE TITLE
关于init.vim中NERDTree的配置与README描述不一致的问题

### ISSUE THREAD

**Issue by AbaoFromCUG** [theniceboy/nvim#14]
根据配置文件，我发现并没有对NERDTree进行快捷键配置，而是对coc-explorer进行配置的`tt`快捷键，NERDTree和coc-explorer好像功能重复。

[README](https://github.com/theniceboy/nvim/blob/a713de5ff18acd532bbc7c83627534d9a1d2d72a/README_cn.md#nerdtree)

[init.vim](https://github.com/theniceboy/nvim/blob/7d7a08616d21d788c760eab1c96149c650f2c3e9/init.vim#L665)

**Comment by Innei** [comment]
原作者删除了nerdTree改用coc explorer替代

**Comment by theniceboy** [comment]
Nerdtree我已经不用了，现在在用coc-explorer

**Comment by kevinhwang91** [comment]
作为一个ranger选手，不尝试一波https://github.com/kevinhwang91/rnvimr?

**Comment by theniceboy** [comment]
@kevinhwang91 这个插件我在reddit看到了，感觉可以，使用体验如何？

**Comment by kevinhwang91** [comment]
@theniceboy 最大的特点就是悬浮可调窗口，内置rpc，只要愿意，可以在neovim通过rpc调用ranger的一切方法。做了ueberzug图片预览校正。
其实最初的目的就是通过调整悬浮窗口，把ranger预览的优势发挥到neovim，就不用频繁切换窗口了。

**Comment by theniceboy** [comment]
@kevinhwang91 可以，我今天试试

**Comment by theniceboy** [comment]
@kevinhwang91 原来就是你写的啊233333 我才发现😂

**Comment by kevinhwang91** [comment]
@theniceboy 因为用ranger+neovim的人比较少。看了你b站的视频就发现你可能会喜欢。

**Comment by theniceboy** [comment]
@kevinhwang91 刚才我试了一下，非常好用，我会在我的channel介绍一下。等一会儿我会给你提一个关于readme的issue，有几个改进意见

**Comment by kevinhwang91** [comment]
@theniceboy 谢谢！
