### ISSUE TITLE
代码缩进线条

### ISSUE THREAD

**Issue by wifidu** [theniceboy/nvim#17]
Ｈｉ！我知道你之前用的是indentLine，请问你现在用的是那个插件？因为我发现你的indentLine插件在你的配置文件中消失了．

**Comment by theniceboy** [comment]
我现在不用缩进条，我用tab，然后把tab现实成｜

**Comment by cybaol** [comment]
大佬 我刚刚复制了你的那些关于set的一些配置
里面有个set listchars=tab:\|\ ,trail:▫这个东西 
那些set我全复制到我的配置里了
然后我发现在go语言的缩进还是特别亮 不像你的是阴影的那种

然后我把你的整个配置全部克隆到我的电脑上去了 发现go的缩进是阴影的了
请问我还少配置了什么东西，刚刚排查了好久没排查出来。

**Comment by cybaol** [comment]
> 
> 
> 我现在不用缩进条，我用tab，然后把tab现实成｜

大佬 我刚刚复制了你的那些关于set的一些配置
里面有个set listchars=tab:\|\ ,trail:▫这个东西 
那些set我全复制到我的配置里了
然后我发现在go语言的缩进还是特别亮 不像你的是阴影的那种

然后我把你的整个配置全部克隆到我的电脑上去了 发现go的缩进是阴影的了
请问我少配置了什么东西，刚刚排查了好久没排查出来。

**Comment by cybaol** [comment]
对了 我在init.vim看那个缩进线是阴影的 但在go里面特别亮

**Comment by cybaol** [comment]
![图片](https://user-images.githubusercontent.com/48387783/94946379-a0c6db80-050e-11eb-9732-6bdd1e5e4a51.png)
在go里面显示是这样的
