### ISSUE TITLE
Possible issue with Kitty and fzf ctrl-u /ctrl-e to scroll?

### ISSUE THREAD

**Issue by bndlfm** [theniceboy/nvim#18]
I'm not usually one to ask for him but I'm a bit stumped here. I suspect the problem lies with Kitty but I'm honestly over my head. I've scanned through init.vim and the README.md many times.

When I use anything relating to FZF both Ctrl-U and Ctrl-E don't seem to scroll the list FZF populates when searching. Ctrl-P however does scroll up.

BSPWM w/ Kitty

**Comment by theniceboy** [comment]
Scrolling within fzf is set through fzf default options (an environment variable). By default, they are ctrl j and ctrl k.
