### ISSUE TITLE
rnvimr 重启问题求助

### ISSUE THREAD

**Issue by SmithJson** [theniceboy/nvim#19]
您好，您 rnvimr 那段的配置，我按 R 进入 ranger ，通过 ranger 随便打开一个文件，我想再次打开 ranger 界面, 我又按了一次 R ，就报错了，我想问是我的启动姿势不对，还是其他原因？

 
![image](https://user-images.githubusercontent.com/40036121/80467983-33b48600-8971-11ea-81c9-7e80c2ff6954.png)

![image](https://user-images.githubusercontent.com/40036121/80470087-1503be80-8974-11ea-9fcb-aae7e9a0992f.png)

![5ea7f35ace007_5ea7f35c8b081](https://user-images.githubusercontent.com/40036121/80470022-fbfb0d80-8973-11ea-9434-d17973af3d4e.gif)

**Comment by theniceboy** [comment]
请在@ kevinhwang91 那儿开个issue：

[https://github.com/kevinhwang91/rnvimr](https://github.com/kevinhwang91/rnvimr)

**Comment by kevinhwang91** [comment]
检查一下你的配置是否冲突了，我通过nvim -u mini.vim没办法重现。mini.vim代码如下：
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr', {'do': 'make sync'}
let g:rnvimr_ex_enable = 1
let g:rnvimr_pick_enable = 1
nnoremap <silent> R :RnvimrSync<CR>:RnvimrToggle<CR><C-\><C-n>:RnvimrResize 0<CR>
let g:rnvimr_layout = { 'relative': 'editor',
            \ 'width': &columns,
            \ 'height': &lines,
            \ 'col': 0,
            \ 'row': 0,
            \ 'style': 'minimal' }
let g:rnvimr_presets = [{'width': 0.5, 'height': 0.5}]
call plug#end()
```

**Comment by theniceboy** [comment]
你是不是用mac的？@SmithJson

**Comment by SmithJson** [comment]
是的 @theniceboy

**Comment by theniceboy** [comment]
哈哈我mac上rnvimr的bug也一堆，你这个错误我好像也遇见过，有时候一个tab有文件了就会报错，最近没时间管了回头再说吧... 想折腾的话可以和@kevinhwang91 讨论一下

**Comment by SmithJson** [comment]
好吧，我自己再找找解决方案吧，谢谢了 @theniceboy @kevinhwang91

**Comment by theniceboy** [comment]
![](https://media0.giphy.com/media/tsgNNs93oIbwk/giphy.gif)
