### ISSUE TITLE
初始化安装时的问题

### ISSUE THREAD

**Issue by guolimin1995** [theniceboy/nvim#20]
我 checkhealth 都是通过了 但是 执行 nvim 并没有自动安装 报了一些没有想过命令的错误，

Error detected while processing /Users/zerone/.config/nvim/init.vim:
line  371:
E117: Unknown function: plug#begin
line  373:
E492: Not an editor command: Plug 'tiagofumo/dart-vim-flutter-layout'
line  374:
E492: Not an editor command: Plug 'RRethy/vim-illuminate'
line  375:
..........
E117: Unknown function: plug#end
line  570:
E185: Cannot find color scheme 'deus'
Error detected while processing VimEnter Autocommands for "*":
E492: Not an editor command: PlugInstall --sync | source $MYVIMRC

MAC 系统  咋搞 大佬

**Comment by guolimin1995** [comment]
/usr/local/bin/python3  我python3 的路径改成了这个 有影响吗

**Comment by theniceboy** [comment]
`PlugInstall`一下

**Comment by guolimin1995** [comment]
> `PlugInstall`一下

谢谢回复，是因为 plug.vim 下载不下来，所以就没有自动执行  PlugInstall, 这个文件没有 我是没有 这个 命令的，我手动下载plug.vim 到指定目录 就可以了
