### ISSUE TITLE
nvim写go时的语法检查

### ISSUE THREAD

**Issue by applejwjcat** [theniceboy/nvim#26]
CW您好，之前看您的go语言视频中，在go文件错误的行后面自动显示错误信息，我想知道是怎么弄的。
我已经安装了neovim和coc以及vim-go，但是只是在错误行有一个标记，所以非常想知道您是怎么弄的？帮帮孩子吧，我已经逛了好几天帖子了

**Comment by applejwjcat** [comment]
我也安装了，当鼠标停在错误行时，会有报错信息，但是移开就只有一个错误标记，我想知道你是怎么弄的？

**Comment by theniceboy** [comment]
哦我我知道你问的是啥了，coc settings里有一个virtual text

**Comment by applejwjcat** [comment]
好了，多谢，已经可以了。
