### ISSUE TITLE
非Markdown文件也将触发snippits.vim的配置

### ISSUE THREAD

**Issue by EvanMeek** [theniceboy/nvim#3]
# 问题
经过我的测试，如果分屏或多标签打开不同文件类型(包含Markdown文件)的buffer，那么非Markdown文件也会触发snippits.vim的配置

# 解决方案
修改`snippits.vim`的`inoremap`为:`inoremap <buffer>`

**例子:**
~~~
autocmd Filetype markdown inoremap <buffer> ,l --------<Enter>
~~~

**Comment by theniceboy** [comment]
Ok, I'll fix it later.

For some reason I don't have notification for new issues. Weird.

**Comment by theniceboy** [comment]
Fixed
