### ISSUE TITLE
duplicated keybindings

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/nvim#31]
```vim
" Adjacent duplicate words
noremap <LEADER>dw /\(\<\w\+\>\)\_s*\1
```
```vim
nnoremap <silent><nowait> <LEADER>d :CocList diagnostics<cr>
```
these part are duplicated in `init.vim`

**Comment by Jayleonc** [comment]
我这边有一个问题就是，当我clone 下来后，执行vim，让他自动配置时，有一些文件无法识别和读取，或者找不到等等，如下图
![image](https://user-images.githubusercontent.com/48094400/93762105-8739b000-fc41-11ea-8430-87f56a70e26c.png)
它卡住了...

**Comment by KiteAB** [comment]
> 我这边有一个问题就是，当我clone 下来后，执行vim，让他自动配置时，有一些文件无法识别和读取，或者找不到等等，如下图
> ![image](https://user-images.githubusercontent.com/48094400/93762105-8739b000-fc41-11ea-8430-87f56a70e26c.png)
> 它卡住了...

自己解决或者新开issue  又不是一个repo只能开一个issue

**Comment by theniceboy** [comment]
`dw`我基本不用，但先把这个留着。
