### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by guolimin1995** [theniceboy/nvim#34]
我在go 相关的文件下 ctrl + l  或者 ctrl +p 会出现错误

处理 function <SNR>191_on_stdout[1]..<SNR>191_neocb[58]..52[13]..54[26]..<SNR>189_infoDefinitionHandler 时发生错误:
第    2 行:
E909: Cannot index a special variable

大佬，像vim 下出现类似的错误 是怎么定位到是哪里或者哪个插件出了问题呢

**Comment by theniceboy** [comment]
你在用我的配置？

**Comment by guolimin1995** [comment]
> 你在用我的配置？

95% 是你的设置，我只是加了些主题，改了一点点快捷键

**Comment by theniceboy** [comment]
我用我的配置试了没有这个错误

**Comment by guolimin1995** [comment]
> 我用我的配置试了没有这个错
