### ISSUE TITLE
<letter> 是啥？

### ISSUE THREAD

**Issue by KylinskyChen** [theniceboy/nvim#35]
你好啊～请问 nvim 中，m\<letter\> 是在当前行添加或删除书签，这个 \<letter\> 是个啥？

**Comment by KiteAB** [comment]
英语水平问题……letter就是字母的意思  m<letter>  就是`m`加你想要的字母  用来代表书签  就跟宏定义是一回事

**Comment by KylinskyChen** [comment]
啊，明白了，非常感谢，多谢指教，我英语水平确实有待提高～




    


在2020年09月18日 23:21，David Zhang 写道： 
英语水平问题……letter就是字母的意思  m  就是m加你想要的字母  用来代表书签  就跟宏定义是一回事

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/theniceboy/nvim/issues/35#issuecomment-694930594",
"url": "https://github.com/theniceboy/nvim/issues/35#issuecomment-694930594",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
