### ISSUE TITLE
请问init.vim配置中这里为何要注释掉,coc的gi和其他快捷键冲突了吗

### ISSUE THREAD

**Issue by seyrenus** [theniceboy/nvim#39]
https://github.com/theniceboy/nvim/blob/fb7eec43296607fcbea60976d90d9bbdb380dd20/init.vim#L704

**Comment by theniceboy** [comment]
`gi` 是vim里”回到上次离开写入模式的位置“的快捷键

**Comment by seyrenus** [comment]
感谢回答，那现在coc的显示所有的实现的功能是不是没有配置快捷键呢

**Comment by theniceboy** [comment]
coc有很多很多功能，我只根据我的需要配置了几个
