### ISSUE TITLE
Markdown <++> Usage

### ISSUE THREAD

**Issue by yushangakki** [theniceboy/nvim#4]
您好，我不知道snippets.vim中<++>是怎样使用的，我把snippets加入之后无法跳转(也有nmap <leader><leader>)，您能解释一下吗，谢谢您！

**Comment by theniceboy** [comment]
每当你使用一个snippet产生一个`<++>`的时候，这个`<++>`就相当于是一个placeholder。你可以键入`,f`来跳转到下一个`<++>`。希望我解答了你的问题。
