### ISSUE TITLE
Statusline and Relativenumber 

### ISSUE THREAD

**Issue by EndlessPeak** [theniceboy/nvim#40]
Hey,upvideoer,I have cloned your repo and type all the commands you claimed in the doc,but I do have some problems that cannot resolve.I am feel quite shame to ask the following questions but you get my word that I do really search for a lot of information and cannot get my problems resolved.
The first problem is that the eleline cannot show the current mode of the neovim,normally it should work as follows:after press the i which is u in you config,the statusline reads "insert".But the eleline actually didn't,just highlight the filename instead.Similarly,when I press the v which is balabala in your config(I canceled your colemak maps),it didn't show "visual",actually it shows nothing or just a "1" located at the position where vim displays the characters or strings when people press useless keys in the normal mode. You can see the picture I pick up as follows.One is insert mode,one is visual mode.I guess that it is what you config to make it work such way,but I want it show the current mode,what should I do?
(I changed the colorscheme from deus to xcodelighthc and cancelled some maps,KiteAB tell me it will work at the dark scheme,but I prefer the light one,I wonder how to make the statusline show the corrent mode,I try to change eleline to bufferline,but still don't work)
![1](https://user-images.githubusercontent.com/53530553/104464698-31bd5080-55ee-11eb-9335-27c6baebb187.png)
![2](https://user-images.githubusercontent.com/53530553/104464706-34b84100-55ee-11eb-9547-979f7df13be8.png)
The second problem:I noticed that when I am in normal mode,the number shows in relativenumber,but when I enter insert mode,the number isn't relativenumber any more,it becomes normally.How does it work that way?What's more,the cursor will change from diamonds to vertical moulding,how to cancel that function?
Looking forward to your reply.Yours LiMing.
哎打了这么一长串，中文输入法终于装好了，可惜好的有点晚，有点尴尬。期望大佬能指点迷津，实在是搜索折腾了一天都没搞明白（暴风哭泣）。

**Comment by theniceboy** [comment]
你好，关于你的问题
1. 我把编辑状态（`Normal`或`Insert`）从eleline里去掉了，eleline最左边的颜色会表示当前的编辑模式。如果你想要显示编辑模式的话你可以fork eleline或者安装一个别的statusline插件
2. 我最近装了一个叫`vim-numbertoggle`的插件，它会自动在相对和绝对行号之间切换。如果你不喜欢你可以把它卸载掉。
3. 光标变化是nvim自带的功能。

**Comment by EndlessPeak** [comment]
好的；谢谢大佬解决我的疑惑。
