### ISSUE TITLE
ubuntu neovim 安装后，启动报错

### ISSUE THREAD

**Issue by firfly** [theniceboy/nvim#41]
`Error detected while processing /home/firfly/.config/nvim/init.vim:
line  592:
E185: Cannot find color scheme 'deus'
line 1370:
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: module 'nvim-treesitter.configs' not found:
        no field package.preload['nvim-treesitter.configs']
        no file '/home/firfly/.config/nvim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/nvim-treesitter/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/playground/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/playground/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-bolt/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-bolt/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/nvim-deus/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/nvim-deus/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/eleline.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/eleline.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-scrollstatus/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-scrollstatus/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-hexokinase/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-hexokinase/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-illuminate/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-illuminate/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/fzf.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/fzf.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/LeaderF/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/LeaderF/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/rnvimr/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/rnvimr/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-rooter/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-rooter/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/any-jump.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/any-jump.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vista.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vista.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/coc.nvim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/coc.nvim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/tmux-complete.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/tmux-complete.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-snippets/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-snippets/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/undotree/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/undotree/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/fzf-gitignore/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/fzf-gitignore/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-gitgutter/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-gitgutter/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/agit.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/agit.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/lazygit.nvim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/lazygit.nvim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-maktaba/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-maktaba/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-codefmt/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-codefmt/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/undotree/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/undotree/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/fzf-gitignore/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/fzf-gitignore/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-gitgutter/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-gitgutter/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/agit.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/agit.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/lazygit.nvim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/lazygit.nvim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-maktaba/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-maktaba/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-codefmt/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-codefmt/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/omnisharp-vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/omnisharp-vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-json/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-json/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/jsonc.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/jsonc.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/html5.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/html5.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-closetag/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-closetag/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/dart-vim-plugin/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/dart-vim-plugin/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/swift.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/swift.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-swift/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-swift/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/bullets.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/bullets.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/auto-pairs/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/auto-pairs/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-visual-multi/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-visual-multi/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/tcomment_vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/tcomment_vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/antovim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/antovim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-surround/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-surround/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/wildfire.vim/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/wildfire.vim/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-after-object/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-after-object/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/tabular/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/tabular/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-capslock/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-capslock/lua/nvim-treesitter/configs/init.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-easymotion/lua/nvim-treesitter/configs.lua'
        no file '/home/firfly/.config/nvim/plugged/vim-easymotion/lua/nvim-treesitter/configs/init.lua'
        no f
Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: after_object#enable
Press ENTER or type command to continue
`
然后回车就进入无配置的nvim界面
启动时没有自动安装插件
machine_specific文件生成如下：
`
❯ cat _machine_specific.vim
" please read through this file and change what you need to change

let g:python_host_prog='/usr/bin/python2'
let g:python3_host_prog='/usr/bin/python3'

let g:mkdp_browser = 'chromium'
let g:mkdp_browserfunc = 'open '

let g:flutter_default_device = 'iPhone\ 11\ Pro'
let g:flutter_run_args = "--flavor dev"
`
是不是还需要手动安装什么？

**Comment by firfly** [comment]
问题解决，不能用0.4.4的稳定版本，需要从github下载源码编译才能使用，最新版本源码编译后是0.5版

**Comment by theniceboy** [comment]
https://github.com/theniceboy/nvim#requirements
