### ISSUE TITLE
coc-explorer keyMappings not work

### ISSUE THREAD

**Issue by vincent-fangyuan** [theniceboy/nvim#42]
首先感觉TheCW的B站视频，让我学习到了很多，希望能继续做下去，多分享一些有关archlinux，开源，neovim等等
我在使用您的neovim的配置时，发现coc-explorer使用不了你配置的一些快捷键，后来去weirongxu/coc-explorer下查阅发现:
explorer.keyMappings需要修改为explorer.keyMappings.global
如果你也确认是问题，还请更新下配置，谢谢

**Comment by theniceboy** [comment]
感谢提醒，已修复
