### ISSUE TITLE
从B站来，git clone你的neovim报错

### ISSUE THREAD

**Issue by sukai-cheng** [theniceboy/nvim#43]
mac环境下，按照视频配置后报了错误，大都是文件找不到

**Comment by theniceboy** [comment]
我看到了这个你的提问，一下子就知道问题出在了哪里因为我精确地猜出了你的mac，nvim版本号，并且看到了完整报错信息。

解决方案：把找不到的文件找到。

**Comment by micsama** [comment]
mac brew的nvim版本不对 得自己去github下载relase过得

**Comment by sukai-cheng** [comment]
收到，trying

xing ji ***@***.***> 于2021年3月28日周日 下午4:27写道：

**Comment by ConanEdogawa1** [comment]
您好！我也是直接克隆你的neovim配置的，总是遇到各种问题，您能出一期视频从零开始使用的自己的neovim配置吗？克隆配置后的一些配置，应该怎么去配置
