### ISSUE TITLE
vim与ranger协同使用

### ISSUE THREAD

**Issue by Troublemaker114112** [theniceboy/nvim#46]
Hi, David
     请教一下,我现在经常碰到在打开vim时候需要到一个很远的路径下访问一个文件.  我现在的做法是关掉vim,然后去访问这个文件,
我想问的是有没有办法在vim打开情况下,调出ranger,去找到那个文件.

**Comment by theniceboy** [comment]
https://github.com/kevinhwang91/rnvimr

**Comment by theniceboy** [comment]
在我的配置里，普通模式下`shift`+`R`
