### ISSUE TITLE
I have to press ctrl-p twice to trigger leaderf

### ISSUE THREAD

**Issue by yyb196** [theniceboy/nvim#50]
In normal mode when I press ctrl-p, nothing happened, I have to press ctrl-p again to make leaderf appear.

Is this work by design or some bug exist. If it's a bug how do I dig it out? 

Thanks in advance.

only one place config <c-p>:
```
:verbose map <c-p>
n  <C-P>       * :Leaderf file<CR>
  Last set from ~/.config/nvim/init.vim line xxx
```

**Comment by theniceboy** [comment]
I was unable to reproduce this issue. Please let me know your nvim info.

Maybe a tmux keybinding conflict?

**Comment by yyb196** [comment]
@theniceboy thanks for your reply. 

I finally find out the reason, because I use your nvim config in a docker container,  to use nvim via docker exec, docker exec process by default use `ctrl-p ctr-q` to detach.  I think it's docker who catch my first `ctrl-p` key stroke.

Thanks again for this great project, very helpful to vim newbie like me.

**Comment by theniceboy** [comment]
Good luck coding!
