### ISSUE TITLE
请问vim修改单个按键映射后，与它相结合的按键要怎么一起修改

### ISSUE THREAD

**Issue by ugirc** [theniceboy/nvim#52]
我将`nnoremap H ^`，即 H 跳到行首

而此时我希望按下 `dH` 也能删掉行首，要怎么设置？我试了下还是只能按 `d^`才能删到行首

**Comment by JohanChane** [comment]
`:omap H ^` 即可。

ref: [Operator-pending](https://speakerdeck.com/aryoung/vim-london-custom-motions?slide=8)

`:help  map-overview` 和 `:help Operator-pending` 查看详细资料。
