### ISSUE TITLE
关闭 diagnostic message 的浮窗

### ISSUE THREAD

**Issue by JohanChane** [theniceboy/nvim#53]
我按照 up 的配置，配置之后，会出现一个问题，光标在错误行上移动时会有浮窗，非常影响体验。之后找到的[解决方案](https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-disable-floating-window)。

既然用了 `"diagnostic.virtualText": true`, 加上 `"diagnostic.messageTarget": "echo"` 更加完美。但是视频中，up 没有出现这个问题，是哪个选项关闭浮窗的呢？

**Comment by theniceboy** [comment]
我的配置的话会有浮窗的，因为有些错误会比较长。可以选择把virtualtext选项关掉
