### ISSUE TITLE
hi~请教个关于nvim 的问题

### ISSUE THREAD

**Issue by cai-fuqiang** [theniceboy/nvim#55]
我在Ｂ站的视频发现你的nvim在normal或者insert模式当前行有一些特殊处理，例如json格式文件：
你的nvim显示:
```
{
     "line":"1"       <---当前行
}
```
我的nvim显示:
```
{
      line:1          <---当前行
}
```
请教下，这个是如何做到的呢

**Comment by pCandKa** [comment]
应该是因为隐藏等级
set conceallevel = 3 好像会有这个效果
没有的话再抬高试试
