### ISSUE TITLE
未找到 $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by wandth** [theniceboy/nvim#56]
在windows 平在下安装的时候报错
![image](https://user-images.githubusercontent.com/34237282/128963537-516b6d18-b366-4077-b117-394052e2cf85.png)
windows10 + windows terminal

**Comment by lee-shun** [comment]
我认为`$XDG_CONFIG_HOME` 应该是一个环境变量，是配置文件的路径，假如在win上没有定义的话， 可以将其在`vimrc`文件中改为具体的路径试一下 @wandth

**Comment by lee-shun** [comment]
或者你可以看看这个：
https://superuser.com/questions/365847/where-should-the-xdg-config-home-variable-be-defined/425712

**Comment by yc-zzh** [comment]
Vim the init.vim file, and change all $XDG_CONFIG_HOME to $HOME/.confg, and it works.

**Comment by theniceboy** [comment]
可以把$XDG_CONFIG_HOME定义到你的`.config`文件夹的目录。一般在`~/.config`
