### ISSUE TITLE
The cursor.vim script can be replaced with easymotion

### ISSUE THREAD

**Issue by Avimitin** [theniceboy/nvim#57]
Used [hjkl-motion](https://github.com/easymotion/vim-easymotion#hjkl-motions) to replaced your cursor.vim. This can help you forget that keymap is defined in the cursor.vim file. Sourcing those keymaps is also a waste of time.

I am not using vim-easymotion now, the plugin I use is the hop.nvim. Take a look at [hop.nvim](https://github.com/phaazon/hop.nvim#line-mode-hopline), which is really fast and integrates with NeoVIM so well.

You can map the line jumping key to `<Leader>j` or `<Leader>k`, this is a more simple way to jump between lines. Here is my configuration: [[avimitin/nvim](https://github.com/Avimitin/nvim/blob/master/lua/mapping.lua#L68)]

If you have interest, I can create a new PR to help you deleted those keys and replaced them with the plugin.

**Comment by theniceboy** [comment]
不用啦谢谢233333
