### ISSUE TITLE
安装COC-tailwind出错，npm WARN old lockfile

### ISSUE THREAD

**Issue by zhichucode** [theniceboy/nvim#60]
![image](https://user-images.githubusercontent.com/43780800/142751485-b384d560-151b-4b44-a3c9-6026accad20b.png)
请问一下，这个问题有朋友遇到过吗，搜索了很多都没有解决。

**Comment by yc-zzh** [comment]
已解决，谢谢
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
