### ISSUE TITLE
在termux中安装遇到一些问题

### ISSUE THREAD

**Issue by chenkeao** [theniceboy/nvim#61]
`Error detected while processing /data/data/com.termux/files/home/.config/nvim/init.vim:                            line   36:                                                                                                         E484: Can't open file /nvim/_machine_specific.vim                                                                  line  206:                                                                                                         E484: Can't open file /nvim/cursor.vim                                                                             line  294:                                                                                                         E484: Can't open file /nvim/md-snippets.vim                                                                        vim-hexokinase needs updating. Run `make hexokinase` in project root. See `:h hexokinase-installation` for more inf
o.
Press ENTER or type command to continue`

**Comment by theniceboy** [comment]
hexokinase 需要go

其他见#62

**Comment by antx-code** [comment]
- 在这个[Error: vim-hexokinase needs updating](https://github.com/RRethy/vim-hexokinase/issues/69) issue中提到的方法解决了hexokinase的问题
- 具体为:先安装go环境，然后删除vim-hexokinase插件的目录，重新执行PlugInstall即可。
- ![DeepinScreenshot_select-area_20220324150719](https://user-images.githubusercontent.com/7877940/159861810-bc4f224d-3b54-4bbe-a1c5-fa357db5a01b.png)
