### ISSUE TITLE
每次启动报错

### ISSUE THREAD

**Issue by myy520** [theniceboy/nvim#62]
处理 /Users/meet/.config/nvim/init.vim 时发生错误:
第   36 行:
E484: 无法打开文件 /Users/meet/.confg/nvim/_machine_specific.vim
第  206 行:
E484: 无法打开文件 /Users/meet/.confg/nvim/cursor.vim
第  294 行:
E484: 无法打开文件 /Users/meet/.confg/nvim/md-snippets.vim
请按 ENTER 或其它命令继续

**Comment by antx-code** [comment]
一样的问题

**Comment by theniceboy** [comment]
试一试`fzf-lua`这个branch，是我正在用的。应该修复了

**Comment by antx-code** [comment]
@theniceboy  @myy520 
- 通过这个issue解决了，提交了一个合并请求https://github.com/theniceboy/nvim/pull/65
