### ISSUE TITLE
能问个特别弱智的问题吗，安装方向的

### ISSUE THREAD

**Issue by jackyliu16** [theniceboy/nvim#64]
系统方面我使用的是window10 wsl2 ubuntu20.04 TLS
在安装那个coc的时候PlugInstall显示安装成功了，但是回到nvim的界面没有办法正常使用这个功能【我重启了】
包括CocInstall ，Coconfig这些功能，仿佛都在提示我没有正常的安装coc...
【曾经有在物理机上安装成功，之前自己装的时候看不懂coc的那个咋安装c语言支持的情况 ...就死活看不懂那个配置（其实是我想删当前目录的所有文件重新搞时，失误删根了），不得已重装系统了，现在也找不到当时咋搞的】

**就想参考下您的配置，想问下这个库的具体使用方式是直接将init.vim和coc-setting 复制到我自己的位置就可以了吗**

就是这个地方，贼懵
C/C++/Objective-C
Using [clangd](https://clang.llvm.org/extra/clangd/Installation.html) with [coc-clangd](https://github.com/clangd/coc-clangd) or:

"languageserver": {
  "clangd": {
    "command": "clangd",
    "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
    "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"]
  }
}
Like many tools, clangd relies on the presence of a [JSON compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html)

Using [ccls](https://github.com/MaskRay/ccls)

"languageserver": {
  "ccls": {
    "command": "ccls",
    "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
    "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".hg/"],
    "initializationOptions": {
        "cache": {
          "directory": "/tmp/ccls"
        }
      }
  }
}

**Comment by theniceboy** [comment]
试一下sudo npm i -g neovim

**Comment by jackyliu16** [comment]
很抱歉稍微晚了点回复..刚刚回到家里，
在尝试过你给的指令之后可以进入到nvim的页面，然后在命令模式下输入Cocinfo有快速补全框出现，应该是插件成功安装了？
但是具体到指令的执行上似乎还是没有啥反应的样子...
我发现运行nvim的时候有个报错，与【https://github.com/nix-community/home-manager/issues/1308】的有点类似，但是我是在'~/.config/coc’下出的问题，也尝试过那个问题下方提供的方法，没有解决问题。
我尝试跟随他的报错帮他创建对应的文件，但是似乎创建完之后就报'~/.config/coc/extensions’没有权限mkdir，我创建完就defined了...

我准备重装下这个wsl2下的Ubuntu...然后再从头开始配置一遍

**Comment by theniceboy** [comment]
:checkhealth一下

**Comment by theniceboy** [comment]
这个问题和这个配置文件没什么太大的关系，主要是coc的配置步骤需要注意一下。先关闭了
