### ISSUE TITLE
执行 nvim 报错~

### ISSUE THREAD

**Issue by demigodliu** [theniceboy/nvim#66]
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/03/0292a7857e485875.png)
请问该问题如何解决？

**Comment by theniceboy** [comment]
需要go

**Comment by demigodliu** [comment]
> 需要go
哦哦，安装 make hexokinase 时看到提示了，说的 go: command not found
正在安装了~感谢，哈哈哈哈哈
