### ISSUE TITLE
Why invalid

### ISSUE THREAD

**Issue by 18123093625** [theniceboy/nvim#7]
I used to  program on Pycharm,however . I have watched your video on bilibili,I git clone nvim in my macOS,but it did not work.The first time I run nvim in terminal,it became blue and ```[coc.nvim] Error on install coc-vimlsp: Error: read ECONNRESET ```on screen.How can I solve the problem  Thanks  so much

**Comment by theniceboy** [comment]
PLEASE, AT LEAST, READ THE README

Please do `:checkhealth` first.

Your terminal was blue probably because you were using the default macOS terminal, which only supports 16 colors. You might want to consider using iTerm, which supports 256 colors.

Again RTFM.
