### ISSUE TITLE
大神，您好，QQ群已经满员了，能新建个QQ群吗？

### ISSUE THREAD

**Issue by WrathGluttony** [theniceboy/nvim#70]
大神，您好，QQ群已经满员了，能新建个QQ群吗？谢谢
想咨询neovim的使用问题

**Comment by theniceboy** [comment]
不好意思那个群不是我的哈哈😂 你要是有问题的话可以给我发邮件。如果和这个repo有关系的话可以开issue

**Comment by WrathGluttony** [comment]
> 不好意思那个群不是我的哈哈😂 你要是有问题的话可以给我发邮件。如果和这个repo有关系的话可以开issue

大神，您好，学习neovim有什么好的论坛、QQ群、TG群推荐吗？
