### ISSUE TITLE
failed to load pyhton3 host

### ISSUE THREAD

**Issue by Arrake-One** [theniceboy/nvim#74]
![image](https://user-images.githubusercontent.com/67113472/173750448-16249491-72ee-4b69-9e42-417130d72ede.png)
```
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
```
messages info:
![image](https://user-images.githubusercontent.com/67113472/173751932-26c63c42-694f-4b8f-8599-8ca71e1276a0.png)
```
function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[12]..provider#Poll, line 7
Vim(if):Error invoking 'poll' on channel 6:^@ch 6 was closed by the client
```
run in wsl

**Comment by theniceboy** [comment]
https://github.com/theniceboy/nvim#after-installation-you-need-to
