### ISSUE TITLE
Two useful plugins

### ISSUE THREAD

**Issue by tanloong** [theniceboy/nvim#77]
You really need to try them:

[AutoSave](https://github.com/Pocco81/AutoSave.nvim), as the name suggests, can reduce your finger efforts.

[vim-slime](https://github.com/jpalardy/vim-slime) can send codes to a specified X11 terminal.

**Comment by theniceboy** [comment]
Thank you for suggesting! I really appreciate it!

**Comment by tanloong** [comment]
😀
