### ISSUE TITLE
nvim init.vim 586行文件配置问题

### ISSUE THREAD

**Issue by muwuren** [theniceboy/nvim#8]
使用插件`coc.nvim`，无法进行函数跳转，发现`init.vim`第586行至590行配置问题，即
` can't use noremap for <Plug>` ， 即 使用<Plug>不能同时使用noremap，将noremap更改为nmap即可。
详见：
https://github.com/neoclide/coc.nvim/issues/1207

**Comment by theniceboy** [comment]
OK，但有意思的是，我一直可以函数跳转2333

**Comment by theniceboy** [comment]
很奇怪，我一直可以跳转，我去看看
