### ISSUE TITLE
来自B站的催更

### ISSUE THREAD

**Issue by AllTheLife** [theniceboy/nvim#80]
大佬，抱歉以这样的方式打扰您，可您已经咕咕了好久了(doge

**Comment by flyingpig233-cpu** [comment]
这个issue质量很高（

**Comment by AllTheLife** [comment]
> 这个issue质量很高（

主要是因为实在忍不下去了:(
我都开始怀疑up主忘记自己的b站账号了(

**Comment by AllTheLife** [comment]
希望大佬能原谅我这个冒昧的行为

**Comment by theniceboy** [comment]
没事没事，我是一直比较忙，最近在打工，希望开学了能继续做吧

感谢你的支持
