### ISSUE TITLE
Throwing `<++>` to the black hole register would be nice

### ISSUE THREAD

**Issue by tanloong** [theniceboy/nvim#81]
[This](https://github.com/theniceboy/nvim/blob/b1a97b348e0cb96d8e68b8ce55cbd8717951d518/init.vim#L237) is the keybinding in question.

When jumping to the next placeholder, the `c` command in the keybinding will by default fill the unamed register `"` with `<++>`. This causes loss of the original text in `"` and therefore has a side effect: After jumping, pressing `p` in normal mode gives `<++>` instead of the one you want to paste.

The above problem can be avoided by using the black hole register `_`.

original keybinding:
`noremap <LEADER><LEADER> <Esc>/<++><CR>:nohlsearch<CR>c4l`
new keybinding:
`noremap <LEADER><LEADER> <Esc>/<++><CR>:nohlsearch<CR>"_c4l`

**Comment by theniceboy** [comment]
Thanks!
