### ISSUE TITLE
add the ruby and rust to the init.vim and try to press to r to run ... it just save and can not run ruby and rust

### ISSUE THREAD

**Issue by gorust666** [theniceboy/nvim#88]
![image](https://user-images.githubusercontent.com/116960518/230600282-ba051296-4322-486b-9601-579dd7cfce93.png)
i just put it to the sentence to the init.vim

	elseif &filetype == 'rb'
		set splitbelow
		:sp
		:term ruby %
	elseif &filetype == 'rust'
		set splitbelow
		:sp
		:term rustc %< && time ./%<

when i press r to run it.

it just to save and not to run

it like this

![image](https://user-images.githubusercontent.com/116960518/230600640-a2a3ba3d-4c58-4c86-b99c-a8f429e75a25.png)

but it run python is good

![image](https://user-images.githubusercontent.com/116960518/230600803-dd9d562c-66c0-4a95-aa04-4cf0eabdc48e.png)

so how to solve it.

please tell me , thanks.....

**Comment by gorust666** [comment]
add the ruby and rust-plug can solute it.

and my sentence addition is 

" Ruby
Plug 'vim-ruby/vim-ruby', { 'for': ['ruby', 'vim-plug'] }

" Rust
Plug 'rust-lang/rust.vim', { 'for': ['rust', 'vim-plug'] }


so it work.

![image](https://user-images.githubusercontent.com/116960518/230655122-5dbfb598-f166-49fc-b0ed-274b7fb3b4f8.png)

**Comment by theniceboy** [comment]
Yeah I encourage you to fork the repo for your personal use.

**Comment by gorust666** [comment]
ok I will try it
