### ISSUE TITLE
WARNING: bibtex is not executable, so bibtex completions are disabled.

### ISSUE THREAD

**Issue by Wjinlei** [theniceboy/nvim#9]
WARNING: bibtex is not executable, so bibtex completions are disabled.
 19   - ERROR: Selected viewer is not executable!
 20     - ADVICE:
 21       - - Selection: llpp
 22   - ERROR: g:vimtex_compiler_method (`latexmk`) is not executable!
 23

这个是什么问题，还需要安装什么东西吗？

**Comment by theniceboy** [comment]
要装的东西都在你提的问题里
