### ISSUE TITLE
config about hlchunk.nvim

### ISSUE THREAD

**Issue by shellRaining** [theniceboy/nvim#95]
hi, there are some place that I don't understand, such as why we use "init" instead of "config" for configuration, and why add this autocmd, `CursorMoved` is quite cost time I think, there is no need to execute `EnableHL` each time move cursor.

https://github.com/theniceboy/nvim/blob/lua-migration/lua/config/plugins/indent.lua#L4-L6

maybe can change to 

```lua
config = function()
	require('hlchunk').setup({
		chunk = {
			enable = true,
			use_treesitter = true,
			style = {
				{ fg = "#806d9c" },
			},
		},
		indent = {
			chars = { "│", "¦", "┆", "┊", },
			use_treesitter = false,
		},
		blank = {
			enable = false,
		},
		line_num = {
			use_treesitter = true,
		},
	})
end
```

**Comment by theniceboy** [comment]
For some reason if I don't add the autocmd the highlights won't update. Are you seeing this?

**Comment by shellRaining** [comment]
🤣oh oh I know, when  open a dart file, the chunk will not render for some reason... I will fix this as soon as possible

**Comment by theniceboy** [comment]
@shellRaining Salute

**Comment by shellRaining** [comment]
add dart support in [0d3c1af](https://github.com/shellRaining/hlchunk.nvim/commit/0d3c1afa76986a138c60db668fac63334a7e1fd6)
